# This script was shamelessly lifted from the dash project.
#
# See https://github.com/magnars/dash.el

language: emacs-lisp
sudo: no
env:
 - EVM_EMACS=emacs-26.1-travis
 - EVM_EMACS=emacs-git-snapshot-travis
install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
script:
./run-travis-ci.sh